# Generated by Django 5.1.6 on 2025-02-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_redirects_tg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('user_agent', models.TextField()),
                ('referer', models.TextField()),
                ('host', models.TextField()),
                ('method', models.TextField()),
                ('server_name', models.TextField()),
                ('server_port', models.TextField()),
                ('server_host', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reviews',
            name='estimation',
            field=models.TextField(),
        ),
    ]
