# Generated by Django 5.1.6 on 2025-02-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_system_contacts_system_redirects_tg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('login', models.TextField()),
                ('message', models.TextField()),
                ('system', models.TextField()),
            ],
        ),
    ]
