# Generated by Django 5.1.6 on 2025-02-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_system_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_redirects_tg',
            name='date',
            field=models.DateField(null='no'),
            preserve_default='no',
        ),
    ]
