# Generated by Django 5.1.6 on 2025-02-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_system_redirects_tg_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='System_redirects_tg',
        ),
    ]
