# Generated by Django 5.1.6 on 2025-02-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.TextField(),
        ),
    ]
